from typing import Protocol


class AudioPlaybackPort(Protocol):
    def play_single(self, path, owner): ...
    def toggle_playlist(self, paths, owner): ...
    def stop(self): ...
    def owns(self, owner): ...
